library(R.oo)


### Name: abort
### Title: Aborts the current expression call
### Aliases: abort.default abort abort.condition
### Keywords: error internal

### ** Examples
## Not run: 
##D  foo <- function() {
##D   cat("foo()...\n")
##D   on.exit(cat("foo()...done\n"))
##D   tryCatch({
##D     stop("Woops!")
##D   }, error = function(ex) {
##D     cat("An error was caught: ", ex$message, "\n", sep="")
##D   })
##D   cat("Continuing...\n")
##D }
##D 
##D bar <- function() {
##D   cat("bar()...\n")
##D   on.exit(cat("bar()...done\n"))
##D   tryCatch({
##D     abort("Woops!")
##D   }, error = function(ex) {
##D     cat("An error was caught: ", ex$message, "\n", sep="")
##D   })
##D   cat("This message will never be displayed...\n")
##D }
##D 
##D # An error generated by stop() can be caught
##D foo()
##D 
##D # ...which is not possible when using abort()
##D bar()
##D 
##D # This expression is never reached
##D cat("This line will never be outputted.\n")
##D 
## End(Not run)


